-- Userテーブル定義
-- 想定DB: H2 / MySQL互換（PostgreSQLを使う場合はAUTOINCREMENT部分をBIGSERIALやIDENTITYに置換してください）
CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_by BIGINT,
  version BIGINT NOT NULL DEFAULT 0
);
